### ISSUE TITLE
Reverted to older version of app?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#146] opened 2023-06-21 15:49 UTC
For example the change from https://github.com/srophe/britishLibrary/issues/86 seems to have reverted?

**Comment by wsalesky** [comment] 2023-06-21 17:44
A bug in how the XSLT handled integers caused a xslt fix that caused a regression (the workflow seems to be keeping things up to date). Fixed now.

**Closed by wsalesky** 2023-06-21 17:44 UTC
Labels: bug, Bill2VU
